using Microsoft.AspNetCore.Diagnostics;
using PlacementCellManagementAPI.Business_Logic;
using PlacementCellManagementAPI.Interface;
using PlacementCellManagementAPI.Models;
using System.Net;

namespace PlacementCellManagementAPI.Handlers
{
    public static class ExceptionHandler
    {
        /// <summary>
        /// Configures the global exception handling middleware.
        /// </summary>
        /// <param name="app">The application builder instance.</param>
        public static void ConfigureExceptionHandler(this IApplicationBuilder app)
        {
            app.UseExceptionHandler(appError =>
            {
                appError.Run(async context =>
                {
                    context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                    context.Response.ContentType = "application/json";

                    var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
                    if (contextFeature != null)
                    {
                        IExceptionLogger logger = new BLException();
                        logger.Log($"Something went wrong: {contextFeature.Error}");

                        await context.Response.WriteAsync(new ErrorDetail()
                        {
                            StatusCode = context.Response.StatusCode,
                            Message = "Internal Server Error. Error generated by NLog!"
                        }.ToString());
                    }
                });
            });
        }
    }
}
